config/routes.rb
Rails.application.routes.draw do
  resources :maps

  root 'maps#index'

end

app/models/map.rb
class Map < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:username, :time, :track)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tracker1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :track %><br>
    <%= f.text_field :track %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<!-- google maps styling -->
  <style type="text/css">
      html, body, #map-canvas { height: 100%; margin: 0; padding: 0;}
   </style>
   <!-- google maps API -->
   <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCpCB3BHytsBFs_VoRm1oPf32x30jgECBc">
   </script>

   <script type="text/javascript">
      function initialize() {

        var locations = [
          {
            lat:33.0500,
            lng:-118.25000,
            title: "marker 1"
          },
          {
            lat:34.0500,
            lng:-118.25000,
            title: "home marker"
          },
          {
            lat:35.0500,
            lng:-118.75000,
            title: "marker 2"
          },
          {
            lat:32.0500,
            lng:-118.95000,
            title: "marker 3"
          },
        ];

        var myLatlng = new google.maps.LatLng(34.0500,-118.25000);

        var marker = new google.maps.Marker()

        var mapOptions = {
          center: { lat: 34.0500, lng: -118.25000},
          zoom: 7
        };
        var map = new google.maps.Map(document.getElementById('map-canvas'),
            mapOptions);
        
          for (var i=0; i<locations.length; i++) {
            var marker= new google.maps.Marker({
            position: new google.maps.LatLng(locations[i].lat, locations[i].lng),
            map: map,
            title: locations[i].title
          });
          }
      var infowindow = new google.maps.InfoWindow({
      content: 'Welcome to LA'
      });
        
      google.maps.event.addListener(marker, 'click', function() {
        infowindow.open(map,marker);
      });
        
      }
      google.maps.event.addDomListener(window, 'load', initialize);
   </script>

   <script src="http://code.jquery.com/jquery-1.4.2.min.js"></script>
    <script>

        jQuery(window).ready(function(){
            gMapInit();
            jQuery("#watchPositionBtn").click(initiate_watchlocation);
            jQuery("#stopWatchBtn").click(stop_watchlocation);
        });
        function gMapInit(){
          var google_tile = "http://maps.google.com/maps/api/staticmap?sensor=false&center=-34.397,150.644&zoom=8&size=300x400"
          jQuery("#googleMap").html(
              jQuery(document.createElement("img")).attr("src", google_tile)
          );
        }
        var watchProcess = null;

        function initiate_watchlocation() {
          if (watchProcess == null) {
              watchProcess = navigator.geolocation.watchPosition(handle_geolocation_query, handle_errors);
          }
        }

        function stop_watchlocation() {
          if (watchProcess != null)
          {
              navigator.geolocation.clearWatch(watchProcess);
              watchProcess = null;
          }
        }

        function handle_errors(error)
        {
            switch(error.code)
            {
                case error.PERMISSION_DENIED: alert("user did not share geolocation data");
                break;

                case error.POSITION_UNAVAILABLE: alert("could not detect current position");
                break;

                case error.TIMEOUT: alert("retrieving position timedout");
                break;

                default: alert("unknown error");
                break;
            }
        }

        function handle_geolocation_query(position) {
          var text = "position.coords.latitude: "  + position.coords.latitude  + "<br/>" +
                     "position.coords.longitude: " + position.coords.longitude + "<br/>" +
                     "position.coords.altitude: " + position.coords.altitude + "<br/>" +
                     "position.coords.accuracy(meters): "  + position.coords.accuracy  + "<br/>" +
                     "position.coords.altitudeAccuracy(meters): "  + position.coords.altitudeAccuracy  + "<br/>" +
                      "position.coords.heading: "  + position.coords.heading  + "<br/>" +
                      "position.coords.speed: "  + position.coords.speed  + "<br/>" +
                     "position.timestamp: " + new Date(position.timestamp);
          jQuery("#APIReturnValues").html(text);
          jQuery("#APIReturnValues").css("border","3px solid green");

          var image_url = "http://maps.google.com/maps/api/staticmap?sensor=false&center=" + position.coords.latitude + ',' + position.coords.longitude +
                          "&zoom=14&size=300x400&markers=color:blue|label:S|" + position.coords.latitude + ',' + position.coords.longitude;
          
          jQuery("#googleMap").html(
              jQuery(document.createElement("img")).attr("src", image_url)
          );
        }
    </script>
  

</head>
<body>
  <div>
      <button id="watchPositionBtn" >Watch Current Position</button>
      <button id="stopWatchBtn" >Stop Watch Position</button>
    </div>
    <div id="APIReturnValues"></div>
    <div id="googleMap" style=" padding:1px; border:1px solid; height:400px; width:300px;">
  </div>
  

<%= yield %>
<h1>Listing maps</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Time</th>
      <th>Track</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each do |map| %>
      <tr>
        <td><%= map.username %></td>
        <td><%= map.time %></td>
        <td><%= map.track %></td>
        <td><%= link_to 'Show', map %></td>
        <td><%= link_to 'Edit', edit_map_path(map) %></td>
        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Map', new_map_path %>

</body>
</html>

app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @map.username %>
</p>

<p>
  <strong>Time:</strong>
  <%= @map.time %>
</p>

<p>
  <strong>Track:</strong>
  <%= @map.track %>
</p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>